name: hopper
channels:
  - conda-forge
  - defaults
dependencies:
  # Core stack
  - python>=3.6
  - numpy
  - scipy
  - matplotlib
  - scikit-image
  - keras
  - pandas
  - scikit-learn
  - opencv
  - pip
  - pip:
    - zmq
    - regional
    - thunder-extraction
    - pymatbridge
  - requests

  # Testing
  - pytest

  # Dev tooling
  - ipython
